const assert=require('assert').strict;
const fs=require('fs');
const vm=require('vm');
const pending=[];
const context=vm.createContext({console,document:{},window:{confirm:()=>true},api:(url,options)=>new Promise((resolve,reject)=>pending.push({url,options,resolve,reject})),toast:()=>{}});
const source=fs.readFileSync('static/app.js','utf8');
vm.runInContext(source.slice(0,source.indexOf('async function api('))+'\nrenderWorkspaceState=()=>{};',context);
const run=code=>vm.runInContext(code,context);
(async()=>{
  run("state.chatMode='standard';state.conversation={id:'a'}");
  const first=run('loadWorkspaceFiles()');
  run("state.conversation={id:'b'}");
  const second=run('loadWorkspaceFiles()');
  pending[1].resolve({files:[{path:'b.txt'}]});await second;
  pending[0].resolve({files:[{path:'a.txt'}]});await first;
  assert.equal(run('state.workspaceFiles[0].path'),'b.txt');
  run("state.chatMode='agent'");
  const old=run('loadWorkspaceFiles()');
  const fresh=run('loadWorkspaceFiles()');
  pending[3].resolve({files:[{path:'new.txt',backend:'agent'}]});await fresh;
  pending[2].resolve({files:[{path:'old.txt',backend:'agent'}]});await old;
  assert.equal(run('state.workspaceFiles[0].path'),'new.txt');
  const deleting=run("deleteAgentWorkspaceFile({currentTarget:{dataset:{agentWorkspaceDelete:'new.txt'}}})");
  assert.equal(pending[4].options.method,'DELETE');
  run("state.chatMode='standard';state.conversation={id:'c'}");
  const current=run('loadWorkspaceFiles()');
  pending[5].resolve({files:[{path:'c.txt'}]});await current;
  pending[4].resolve({files:[{path:'agent-only.txt',backend:'agent'}]});await deleting;
  assert.equal(run('state.workspaceFiles[0].path'),'c.txt');
  assert.equal(run('state.workspaceContext'),'standard:c');
  console.log('PASS: conversation switch, out-of-order refresh, delete/mode-switch races');
})().catch(error=>{console.error(error);process.exitCode=1});
